language: r
pandoc_version: 2.2.1
cache: packages

script:
  - Rscript -e "blogdown::install_hugo()"
  - Rscript -e "setwd('site'); blogdown::build_site()"

after_success:
  - chmod +x ./deploy.sh
  - ./deploy.sh
