---
output: rmarkdown::md_document
---

# Datas Importantes #


```{r, echo=FALSE, results="asis"}

da <- data.frame(
    task = c("Envio de trabalhos para comunicação oral",
             "",
             "Resultado da avaliação dos trabalhos para comunicação oral",
             "",
             "Incrições para o evento",
             ""),
    deadline = c("15/10/2018 (Segunda-feira)",
                 "01/11/2018 (Quinta-feira)",
                 "29/10/2018 (Segunda-feira)",
                 "09/11/2018 (Sexta-feira)",
                 "01/11/2018 (Sexta-feira)",
                 "12/11/2018 (Segunda-feira)"),
    stringsAsFactors = FALSE
)

library(kableExtra)
da[c(1, 3, 5), 2] <- cell_spec(da[c(1, 3, 5), 2], strikeout = TRUE)
da[c(2, 4, 6), 2] <- cell_spec(da[c(2, 4, 6), 2], bold = TRUE, color = "red")
knitr::kable(da, col.names = c("", "Data limite"), escape = FALSE)

```

---

## Inscrição e submissão de trabalhos ##


**A submissão de trabalhos inscrições online estão
  encerradas. Interessados que não fizeram a inscrição previamente,
  podem fazer a inscrição durante recepção do evento (quarta-feira das
  8:00 às 8:30).**

A taxa de **inscrição** para o VII Encontro dos Alunos em Estatística e
Experimentação Agronômica é de **R$20,00**, o que inclui todas as
atividades do evento (minicurso, conferências, comunicações orais e mesa
redonda). A inscrição é confirmada com o envio do comprovante de
pagamento para jreduardo@usp.br. O pagamento pode ser realizado de duas
maneiras:

1. Em dinheiro, em dinheiro com a secretária Solange de Assis Paes
   Sabadin (tel. (19) 3429-4127, ramal 231), na sala da Pós-Graduação,
   3º andar do pavilhão de Engenharia da ESALQ, Avenida Pádua Dias,
   13418-900, Piracicaba, SP; ou

2. Via depósito/tranferência bancária para Eduardo E. Ribeiro Junior,
   Agência 5930-7 (Banco do Brasil), Conta: 1.876-7.


Na **submissão de trabalhos** para apresentação em formato de
comunicação oral, com duração de 20min, sendo 17min de apresentação e
3min de discussão, solicita-se apenas o título e resumo do artigo em
português e inglês. O escopo do evento é a apresentação de artigos
originais que explorem, promovam e/ou estendam métodos aplicados da
Estatística. Todos os títulos e resumos dos trabalhos aceitos serão
publicados nos anais do evento. Portanto, ao submeter seu trabalho,
entende-se que todos os autores estão de acordo com sua publicização.
