---
output: rmarkdown::md_document
---

<div style='text-align: center; margin-bottom: -10px'>
  <p><strong>Minicurso</strong>:
    21/11 (9h às 12h00) e 22/11 (8h30 às 12h30)<br/>
  <strong style='font-size: 1.2em'>
    Modelos de regressão não linear: teoria e aplicações
  </strong><br/>
  <a href="http://www.leg.ufpr.br/~walmes/"><strong>
    Prof. Dr. Walmes Marques Zeviani
  </strong></a> (LEG/UFPR)<br/>
</div>

_Em modelos regressão não-linear dados observados de uma variável
resposta são descritos por uma função de uma ou mais variáveis
explicativas que é não linear seus parâmetros. Assim como nos modelos
lineares o objetivo é identificar e estabelecer a relação entre
variáveis explicativas e resposta. Entretanto, enquanto os modelos
lineares definem, em geral, relações empíricas, os modelos não-lineares
são, em grande parte das vezes, motivados pelo conhecimento do tipo de
relação entre as variáveis. Desta forma, as aplicações surgem nas
diversas áreas onde relações físicas, biológicas, cinéticas, químicas,
fisiológicas, dentre outras, são estabelecidas por funções não lineares
que devem ter coeficientes (parâmetros) identificados (estimados) a
partir de dados observados ou experimentais._

---

<div style='text-align: center; margin-bottom: -10px'>
  <p><strong>Conferência de abertura</strong>:
    21/11 (8h30 às 9h30)<br/>
  <strong style='font-size: 1.2em'>
    An Extended Random-effects Approach to Modeling Repeated,
    Overdispersed Count Data
  </strong><br/>
  <a href="http://ce.esalq.usp.br/equipe/clarice-garcia-borges-demetrio"><strong>
    Profa. Dra. Clarice Garcia Borges Demétrio
  </strong></a> (ESALQ/USP)<br/>
</div>

_Non-Gaussian outcomes are often modeled using members of the so-called
exponential family. The Poisson model for count data falls within this
tradition. The family in general, and the Poisson model in particular,
are at the same time convenient since mathematically elegant, but in
need of extension since often somewhat restrictive. Two of the main
rationales for existing extensions are (1) the occurrence of
overdispersion (Hinde and Demétrio 1998, Computational Statistics and
Data Analysis 27, 151-170), in the sense that the variability in the
data is not adequately captured by the model's prescribed mean-variance
link, and (2) the accommodation of data hierarchies owing to, for
example, repeatedly measuring the outcome on the same subject
(Molenberghs and Verbeke 2005, Models for Discrete Longitudinal Data,
Springer), recording information from various members of the same
family, etc. There is a variety of overdispersion models for count data,
such as, for example, the negative-binomial model. Hierarchies are often
accommodated through the inclusion of subject-specific, random
effects. Though not always, one conventionally assumes such random
effects to be normally distributed. While both of these issues may occur
simultaneously, models accommodating them at once are less than
common. This paper proposes a generalized linear model, accommodating
overdispersion and clustering through two separate sets of random
effects, of gamma and normal type, respectively (Molenberghs, Verbeke
and Demétrio 2007, LIDA, 13, 513-531, Molenberghs et al, 2010,
Statistical Science, 25: 325–347, Vangeneugden et al, 2011, Journal of
Applied Statistics, 38: 215-232, Molenberghs, Verbeke and Demétrio 2017,
SORT, 41, 3-54). This is in line with the proposal by Booth, Casella,
Friedl and Hobert (2003, Statistical Modelling 3, 179-181). The model
extends both classical overdispersion models for count data (Breslow
1984, Applied Statistics 33, 38-44), in particular the negative binomial
model, as well as the generalized linear mixed model (Breslow and
Clayton 1993, JASA 88, 9-25). Apart from model formulation, we briefly
discuss several estimation options, and then settle for maximum
likelihood estimation with both fully analytic integration as well as
hybrid between analytic and numerical integration. The latter is
implemented in the SAS procedure NLMIXED. The methodology is applied to
data from a study in epileptic seizures._

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Conferência &alpha; </strong>:
    21/11 (16h15 às 17h15)<br/>
  <strong style='font-size: 1.2em'>
    Análise de Dados Poisson Composto Longitudinais Multivariado
  </strong><br/>
  <a href="http://www.des.ufscar.br/departamento/docentes-1/afranio-marcio-correa-vieira"><strong>
    Prof. Dr. Afrânio Marcio Corrêa Vieira
  </strong></a> (UFSCar)<br/>
</div>

_Distribuição Poisson Composta é uma distribuição contínua assimétrica,
com massa de probabilidade positiva em $Y=0$. Registros pluviométricos,
valores pagos para apólices de seguros, dentre outras situações
apresentam dados com este comportamento. Apresentaremos um problema em
que múltiplas expressões bioquímicas de variedades do algodão foram
mensuradas ao longo do tempo, sob um delineamento experimental
planejado. Na análise, uma estratégia utilizando modelos lineares
generalizados misto permite a análise multivariada das expressões
bioquímicas, levando em consideração a não-normalidade, dependência
temporal e estrura do delineamento experimental._

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Conferência &beta; </strong>:
    22/11 (16h15 às 17h15)<br/>
  <strong style='font-size: 1.2em'>
    Planejamento para o ajuste de curvas flexíveis
  </strong><br/>
  <a href="http://www.ibb.unesp.br/#!/departamentos/bioestatistica/servidores/luzia-a-trinca/"><strong>
    Profa. Dra. Luzia Aparecida Trinca
  </strong></a> (UNESP/Botucatu)<br/>
</div>

_O ajuste de curvas ou superfícies sempre faz parte da análise de
resultados experimentais, nos quais procura-se estabelecer relações
entre a variável resposta e os vários fatores quantitativos. Os
polinômios de segunda ordem são largamente empregados e suas limitações
frequentes, devido a simetria imposta, não raramente levam à falta de
ajuste e ao uso de modelos de alta ordem nem sempre interpretáveis ou
parcimoniosos. Para curvas ou superfícies assimétricas, inclusive com
assíntotas, na década de 1990, foram sugeridos os polinômios
fracionários, inspirados na família de transformações Box-Tidwell, para
análise de dados observacionais.  Vários trabalhos mostraram que
polinômios fracionários (PF) de até segunda ordem podem gerar uma grande
variedade de curvas úteis para modelar as relações de interesse
prático. Em princípio, os PF podem também resolver os problemas de falta
de ajuste dos modelos de primeira e segunda ordem na análise de dados
experimentais. No entanto, quando tentamos ajustar um PF aos dados de um
experimento, esbarramos em, pelo menos, dois problemas. O primeiro é que
o PF de segunda ordem, como definido originalmente, inclui dois
parâmetros para cada fator, as potências, além dos coeficientes de
regressão. O segundo é que o delineamento clássico apresenta pontos
esparsos e simétricos na região experimental, resultando em pouca
informação para estimação dos parâmetros extras do polinômio. Nesse
trabalho propomos uma versão de PF de segunda ordem que restringe a
estimação de uma única potência para cada fator. A ideia é que a
potência determina a transformação apropriada aos níveis do fator para
que o polinômio de segunda ordem seja uma boa aproximação para a relação
subjacente.  Sob esse modelo mais parcimonioso, estudamos o
comportamento de delineamentos eficientes para estimar todos os
parâmetros. Como o modelo é não linear precisamos incorporar informação
a priori para a construção dos delineamentos. Resultados mostram que o
delineamento resultante para o PF pode ser bem diferente do delineamento
clássico, indicando que o problema de estimação das potências deve ser
considerado no planejamento do experimento. O método pode ser estendido
para os modelos lineares generalizados nas situações em que seja
apropriado especificar o preditor linear por uma relação curva
assimétrica._

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Conferência de encerramento</strong>:
    23/11 (11h00 às 12h00)<br/>
  <strong style='font-size: 1.2em'>
    Alternative methods for modeling of the cure rate in survival
    studies
  </strong><br/>
  <a href="http://www.ufscar.br/~des/docente/vera/vera.htm"><strong>
    Profa. Dra. Vera Lúcia Damasceno Tomazella
  </strong></a> (UFSCar)<br/>
</div>

_In medical studies, it is common that some units under study are not
susceptible to the event of interest, called immune or cured elements. A
class of models, referred to as cure rate models, considers these
situations and has been studied by several authors in the recent
years. The cure fraction is of interest to patients and a useful measure
to monitor trends and differences in survival of curable disease. In
this presentation we discuss some alternative methods for modeling cure
rate in particular the Defective models. Defective models have the
advantage of modeling the proportion of cured without adding any extra
parameters in the model, in contrast to the most models from the
literature._

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Mesa Redonda</strong>:
    23/11 (9h00 às 10h30)<br/>
  <strong style='font-size: 1.2em'>
    Desafios na Pós-graduação em Estatística e Estatística Aplicada
  </strong><br/>
</div>

_Programas de Pós-graduação em Estatística e Estatística Aplicada
apresentam diversos desafios para sua manutenção e melhoria como
aquisição de recursos para ensino, pesquisa e extensão; capacitação de
docentes em novas tecnologias; deficiência na formação dos ingressantes;
divulgação e preenchimento de vagas; valorização da heterogeneidade na
produção científica; entre outros. O objetivo dessa mesa redonda é
compartilhar as dificuldades e soluções tomadas nos programas de
Pós-graduação em Estatística e Experimentação Agronômica (ESALQ/USP),
Interinstitucional de Pós-graduação em Estatística (UFSCar/USP) e de
Especialização em Data Science and Big Data (LEG/UFPR). A mesa redonda
será coordenada pela Profa. Dra. Clarice Demétrio (vice-coordenadora do
PPG-EEA na ESALQ) com participação da Profa. Dra. Vera Tomazella
(coordenadora do PIPGES na UFSCar) e Walmes Zeviani (vice-coordenador da
especialização em DSBD na UFPR)._

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Comunicações orais I</strong>:
    21/11 (13h30 às 15h30)<br/>
</div>

(**13h30-13h50**) <u>Welinton Y. Hirai</u> & Carlos T.S. Dias,\
Imputação múltipla para matriz de interação genótipo e ambiente;

(**13h50-14h10**) <u>Janaína M. Melo</u>, Idemauro A.R. Lara & Sílvia
M. Freitas,\
Seleção de formulações de bebidas prebióticas via Modelos Logitos
Cumulativos Mistos;

(**14h10-14h30**) <u>Alessandra L. Goes</u> & Renata A. Sermarini,\
Delineamentos ótimos para experimentos com cana-de-açucar;

(**14h30-14h50**) <u>Wagner Wolff</u>, Aart Overeem & Remko Uijlenhoet,\
Abordagem geoestatística para mapeamento da chuva a partir de enlaces
comerciais de microondas;

(**14h50-15h10**) <u>Maria L. Salvador</u> & Idemauro A.R. Lara,\
Superdispersão em Dados Categorizados Multinomiais: uma Aplica- ção em
Ciências Agrárias;

(**14h50-15h30**) <u>Maíra B. Fatoretto</u>, Rafael A. Moral & Clarice
G.B. Demétrio,\
Seleção de efeitos do tratamento usando o método bootstrap.

---

<div style='text-align: center; margin-bottom: -10px'>
<p><strong>Comunicações orais II</strong>:
    22/11 (13h30 às 15h30)<br/>
</div>

(**13h30-13h50**) <u>Suelen C. Gasparetto</u>, Sônia M.S. Piedade &
Cristian Villegas,\
Visualização de dados utilizando ggplot2;

(**13h50-14h10**) <u>Fábio Prataviera</u>, Gauss M. Cordeiro, Edwin
M.M. Ortega & Altemir S. Braga,\
A distribuição odd log-logística gama generalizada e modelo de regressão
associado para dados censurados;

(**14h10-14h30**) <u>Andréia P.M. Hilário</u> & César G. Lima,\
Ajuste do modelo Gompertz aos dados de crescimento de frangos de corte

(**14h30-14h50**) <u>Eduardo E.R. Junior</u>, Celeste P. D'Alessandro &
Clarice G.B. Demétrio,\
Impacto de fungos no controle de lagartas Chrysodeixis includens e
Helicoverpa amigera

(**14h50-15h10**) <u>Vivian A. Brancaglioni</u>, Carlos T.S. Dias, Marta
J.A. Coelho & Paulo S. Pavinato,\
Análise do fracionamento de fósforo em solo de cerrado por meio de
técnicas multivariadas

---
